type User {
	id: Int!
	firstname: String!
	lastname: String!
	email: String!
	passsword: String!
	birthdate: String!
	gender: String
	bio: String
	tags: [Tag] @relation(name: "HAS_TAG", direction: "OUT")
	elo: Int!
	prefAge: Int
	prefOrientation: String
	prefRadius: Int
	confirmToken: String!
	resetToken: String!
	likesCount: Int @cypher(statement: "MATCH (User)-[r:LIKED]->(this) RETURN COUNT(r)")
	likedUsers: [User] @relation(name: "LIKED", direction: "OUT")
	likedByUsers: [User] @relation(name: "LIKED", direction: "IN")
    conversations: [Conversation] @relation(name: "HAS_CONV", direction: "OUT")
}

type Tag {
	id: Int!
	name: String!
}

type Conversation {
    id: Int!
    lastMessage: Message @cypher(statement: "MATCH (this)-[:HAS_MSG]-(msgs:Message) RETURN msgs")
    messages: [Message] @relation(name: "HAS_MSG", direction: "OUT")
    members: [User] @relation(name: "HAS_CONV", direction: "IN")
}

type Message {
	id: Int!
    author: User @cypher(statement: "MATCH (author:User {id: this.author_id}) RETURN author")
	content: String!
}

type Blocked @relation(name: "BLOCKED") {
    from: User!
    to: User!
    id: Int!
    at: String!
}

type Book {
  author: String
  title: String
}

type Mutation {
  signup (firstname: String!, email: String!, password: String!): String
  login(email: String!, password: String!): String
}
